name: curl Test

on:
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # This should be a safe limit for the tests to run.
    timeout-minutes: 25
    steps:
    - name: Install test dependencies
      run: |
        sudo apt-get update
        sudo apt-get install nghttp2
        sudo pip install impacket

    - name: Build wolfSSL
      uses: wolfSSL/actions-build-autotools-project@v1
      with:
        path: wolfssl
        configure: --enable-curl
        install: true

    - name: Build curl
      uses: wolfSSL/actions-build-autotools-project@v1
      with:
        repository: curl/curl
        path: curl
        configure: --with-wolfssl=$GITHUB_WORKSPACE/build-dir
        check: false

    - name: Test curl
      working-directory: curl
      run: make -j test-ci
