name: CodeSonar run
on:
  push:
    branches:
      - release/daily
  pull_request:
    branches:
      - 'release/daily'
  #schedule:
  #  - cron: '17 2 * * *'
  

jobs:
  CodeSonar_Analyze:
    permissions: write-all
    runs-on: wolfssl-runner-set
    container:
      image: ghcr.io/codesecure-se/wolfssl-cso-builder:8.2p0
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    env:
      CAFILE: ".github/github.cert.pem"
      TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      API_URL: https://api.github.com
      REQUEST_NUMBER: ${{ github.event.pull_request.number }}
      ROOT_TREE: "WolfSSL-Projects/WolfSSL-GitHub"
      PROJECT_NAME: "wolfssl"
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      COMMIT_HASH: $GITHUB_SHA
      CSONAR_HUB_URL: "https://partnerdemo.codesonar.com"
      CSONAR_HUB_USER: "${{ secrets.CSONAR_HUB_USER }}"
      CSONAR_HUB_PASSWORD: "${{ secrets.CSONAR_HUB_PASSWORD }}"
      CSONAR_CSHOME: /opt/codesonar
      CSO_GITHUB: /opt/codesonar-github
      REPO_URL: "http://github.com/markhermeling/wolfssl"
      TARGET: ${{ github.base_ref }}
      IS_PR: ${{ github.event_name }}
    steps:
      - name: Set parallelism and project name
        run: |
          echo "PARALLEL=`nproc`" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fix ownership warning
        run: git config --global --add safe.directory /__w/wolfssl/wolfssl
      - name: configure
        run: ./autogen.sh ; ./configure --enable-all
      - name: Checkout CodeSonar CI-Script
        uses: actions/checkout@v4
        with:
          repository: CodeSecure-SE/codesonar_ci
          path: codesonar-scripts
      - name: Build and Analyze
        run: python3 codesonar-scripts/build_and_analyze.py codesonar.conf make -j $PARALLEL
      - name: Download results
        run: |
          echo $CSONAR_HUB_PASSWORD > hubpwfile
          $CSONAR_CSHOME/codesonar/bin/codesonar dump_warnings.py --project-file $PROJECT_NAME.prj \
          -auth password -hubuser $CSONAR_HUB_USER -hubpwfile hubpwfile  --hub $CSONAR_HUB_URL --gained-since-previous-analysis --visible-warnings "active" --sarif --sarif-detail brief -o diff.sarif
          $CSONAR_CSHOME/codesonar/bin/codesonar dump_warnings.py --project-file $PROJECT_NAME.prj  \
          -auth password -hubuser $CSONAR_HUB_USER -hubpwfile hubpwfile  --hub $CSONAR_HUB_URL \
          --sort "ascending:priority" --sort "descending:score" --visible-warnings "active" --gained-since-previous-analysis --csv -o diff.csv

          sed -i 's#/warninginstance#https://partnerdemo.codesonar.com/warninginstance#' diff.csv
          sed -i 's#.txt$#.html#' diff.csv
          cut -d, -f1,2,3,4,5,6,7,8,9,15 diff.csv > diff2.csv
          csv2md diff2.csv > diff.md
      - name: Email results
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: CodeSonar results for ${{ github.repository }}
          body: file://diff.md
          convert_markdown: true
          from: "CodeSonar Analyzer"
          to: "mark@hermeling.org, testing@wolfssl.com"
          reply_to: "mark@hermeling.org"
      - name: cleanup
        run: rm hubpwfile
