name: Daily Merge and CodeSonar run
on:
  push:
    branches:
      - release/daily
  pull_request:
    branches:
      - 'release/daily'
  schedule:
    - cron: '17 2 * * *'

jobs:
  Daily_Merge_and_CodeSonar_Analyze:
    permissions: write-all
    runs-on: self-hosted
    container:
      image: canuckmh/wolfssl-cso-builder:7.4p0
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    env:
      CAFILE: ".github/github.cert.pem"
      TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      API_URL: https://api.github.com
      REQUEST_NUMBER: ${{ github.event.pull_request.number }}
      ROOT_TREE: "WolfSSL-Projects/WolfSSL-GitHub"
      PROJECT_NAME: "wolfssl"
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      COMMIT_HASH: $GITHUB_SHA
      CSONAR_HUB_URL: "https://partnerdemo.codesonar.com"
      CSONAR_HUB_USER: "${{ secrets.CSONAR_HUB_USER }}"
      CSONAR_HUB_PASSWORD: "${{ secrets.CSONAR_HUB_PASS }}"
      CSONAR_CSHOME: /opt/codesonar
      CSO_GITHUB: /opt/codesonar-github
      REPO_URL: "http://github.com/markhermeling/wolfssl"    # the github.repositoryUrl is not an http-link.
      TARGET: ${{ github.base_ref }}
      IS_PR: ${{ github.event_name }}
    steps:
      - name: Set parallelism and project name
        run: |
          echo "PARALLEL=`nproc`" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: release/daily
      - name: Fix ownership warning
        run: git config --global --add safe.directory /__w/wolfssl/wolfssl
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: wolfssl/wolfssl
          upstream-branch: daily-snapshot
          branch: release/daily
      - name : configure
        run: ./autogen.sh ; ./configure --enable-all
      - name: Checkout CodeSonar CI-Script
        uses: actions/checkout@v4
        with:
          repository: CodeSecure-SE/codesonar_ci
          path: codesonar-scripts
      - name: Build and Analyze
        run: python3 codesonar-scripts/build_and_analyze.py codesonar.conf make -j $PARALLEL
      - name: Download results
        run: $CSONAR_CSHOME/codesonar/bin/codesonar dump_warnings.py $PROJECT_NAME --gained-since-previous-analysis --sarif --sarif-detail brief -o diff.sarif
      - name: Upload artefact
        uses: actions/upload-artifact@v3
        with:
          name: SARIF results summary
          path: diff.sarif

