name: Generate full report
on:
  schedule:
    - cron: '17 17 * * 0'
  push:
    branches:
      - 'release/**'

jobs:
  Report:
    permissions: write-all
    runs-on: wolfssl-runner-set
    container:
      image: canuckmh/wolfssl-cso-builder:8.0p0
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    env:
        CSONAR_HUB_URL: "https://partnerdemo.codesonar.com"
        CSONAR_HUB_USER: "${{ secrets.CSONAR_HUB_USER }}"
        CSONAR_HUB_PASSWORD: "${{ secrets.CSONAR_HUB_PASS }}"
        CSONAR_CSHOME: /opt/codesonar
    steps:
      - name: Download results
        run: |
          echo $CSONAR_HUB_PASSWORD > hubpwfile
          $CSONAR_CSHOME/codesonar/bin/codesonar dump_warnings.py --project-name "/WolfSSL-Projects/WolfSSL-GitHub/release/daily"  \
          -auth password -hubuser $CSONAR_HUB_USER -hubpwfile hubpwfile  --hub $CSONAR_HUB_URL \
          --show-column "score" --show-column "id" --show-column "project" --show-column "class" --show-column "significance" --show-column "file" --show-column "lineNumber" --show-column "procedure" --show-column "priority" --show-column "url" \
          --sort "ascending:priority" --sort "descending:score" --visible-warnings "active" --csv -o diff.csv
          sed -i 's#/warninginstance#https://partnerdemo.codesonar.com/warninginstance#' diff.csv
          sed -i 's#.txt$#.html#' diff.csv
          csv2md diff.csv > diff.md
      - name: Email results
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: CodeSonar weekly results for ${{ github.repository }}
          body: file://diff.md
          convert_markdown: true
          from: "CodeSonar Analyzer"
          to: "mark@hermeling.org, testing@wolfssl.com"
          reply_to: "mark@hermeling.org"
